// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xocbiaxzultjhkwmcsmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvY2JpYXh6dWx0amhrd21jc214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDg2NzUsImV4cCI6MjA3MjMyNDY3NX0.TLM9tn2Gjf3RurLT4iSFfIk3M0uqpagQzh2XE9JfuXs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});